APPLICATION = test_vtimer_msg
include ../Makefile.tests_common

BOARD_BLACKLIST := arduino-mega2560
# arduino-mega2560: time.h missing from avr-libc

USEMODULE += vtimer

include $(RIOTBASE)/Makefile.include
